// <auto-generated />
using System;
using GambitoServer.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GambitoServer.Migrations
{
    [DbContext(typeof(GambitoContext))]
    [Migration("20250523201922_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_hora", new[] { "banco_horas", "hora_extra" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GambitoServer.Db.DefeitoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("defeito_pkey");

                    b.HasIndex(new[] { "Nome" }, "defeito_nome_key")
                        .IsUnique()
                        .HasDatabaseName("ix_defeito_nome");

                    b.ToTable("defeito", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Db.EtapaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("etapa_pkey");

                    b.ToTable("etapa", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Db.FuncaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("funcao_pkey");

                    b.HasIndex(new[] { "Nome" }, "funcao_nome_key")
                        .IsUnique()
                        .HasDatabaseName("ix_funcao_nome");

                    b.ToTable("funcao", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Db.FuncionarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("Encarregado")
                        .HasColumnType("integer")
                        .HasColumnName("encarregado");

                    b.Property<int?>("Funcao")
                        .HasColumnType("integer")
                        .HasColumnName("funcao");

                    b.Property<bool>("Invativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("funcionario_pkey");

                    b.HasIndex("Encarregado")
                        .HasDatabaseName("ix_funcionario_encarregado");

                    b.HasIndex("Funcao")
                        .HasDatabaseName("ix_funcionario_funcao");

                    b.ToTable("funcionario", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Db.OrgEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<ZonedDateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<ZonedDateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Guid")
                        .HasName("organizacao_pkey");

                    b.ToTable("organizacao", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Db.PedidoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Produto")
                        .HasColumnType("integer")
                        .HasColumnName("produto");

                    b.Property<int>("QtdPecas")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_pecas");

                    b.HasKey("Id")
                        .HasName("pedido_pkey");

                    b.HasIndex("Produto")
                        .HasDatabaseName("ix_pedido_produto");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Db.ProdutoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("TempoPeca")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_peca");

                    b.HasKey("Id")
                        .HasName("produto_pkey");

                    b.HasIndex(new[] { "Nome" }, "produto_nome_key")
                        .IsUnique()
                        .HasDatabaseName("ix_produto_nome");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Db.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoDiaEntity", b =>
                {
                    b.Property<int>("LinhaProducao")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao");

                    b.Property<LocalDate>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<bool>("Invativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invativo");

                    b.HasKey("LinhaProducao", "Data")
                        .HasName("linha_producao_dia_pkey");

                    b.ToTable("linha_producao_dia", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("linha_producao_pkey");

                    b.ToTable("linha_producao", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoHoraDefeitoEntity", b =>
                {
                    b.Property<int>("LinhaProducaoHora")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao_hora");

                    b.Property<bool>("Retrabalhado")
                        .HasColumnType("boolean")
                        .HasColumnName("retrabalhado");

                    b.Property<int>("Defeito")
                        .HasColumnType("integer")
                        .HasColumnName("defeito");

                    b.Property<int>("QtdPecas")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_pecas");

                    b.HasKey("LinhaProducaoHora", "Retrabalhado", "Defeito")
                        .HasName("linha_producao_hora_defeito_pkey");

                    b.HasIndex("Defeito")
                        .HasDatabaseName("ix_linha_producao_hora_defeito_defeito");

                    b.ToTable("linha_producao_hora_defeito", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoHoraEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<LocalDate?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<LocalTime>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<LocalTime?>("HoraFim")
                        .HasColumnType("time")
                        .HasColumnName("hora_fim");

                    b.Property<LocalTime?>("HoraIni")
                        .HasColumnType("time")
                        .HasColumnName("hora_ini");

                    b.Property<int>("LinhaProducao")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao");

                    b.Property<bool>("Paralizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("paralizacao");

                    b.Property<int>("Pedido")
                        .HasColumnType("integer")
                        .HasColumnName("pedido");

                    b.Property<int?>("QtdProduzido")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_produzido");

                    b.Property<TipoHora?>("Tipo")
                        .HasColumnType("tipo_hora")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("linha_producao_hora_pkey");

                    b.HasIndex("Pedido")
                        .HasDatabaseName("ix_linha_producao_hora_pedido");

                    b.HasIndex("LinhaProducao", "Data")
                        .HasDatabaseName("ix_linha_producao_hora_linha_producao_data");

                    b.ToTable("linha_producao_hora", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoHoraEtapaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("Etapa")
                        .HasColumnType("integer")
                        .HasColumnName("etapa");

                    b.Property<int>("LinhaProducaoHora")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao_hora");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Segundos")
                        .HasColumnType("integer")
                        .HasColumnName("segundos");

                    b.HasKey("Id")
                        .HasName("linha_producao_hora_etapa_pkey");

                    b.HasIndex("Etapa")
                        .HasDatabaseName("ix_linha_producao_hora_etapa_etapa");

                    b.HasIndex("LinhaProducaoHora")
                        .HasDatabaseName("ix_linha_producao_hora_etapa_linha_producao_hora");

                    b.ToTable("linha_producao_hora_etapa", (string)null);
                });

            modelBuilder.Entity("LinhaProducaoHoraEtapaFuncionario", b =>
                {
                    b.Property<int>("LinhaProducaoHoraEtapa")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao_hora_etapa");

                    b.Property<int>("Funcionario")
                        .HasColumnType("integer")
                        .HasColumnName("funcionario");

                    b.HasKey("LinhaProducaoHoraEtapa", "Funcionario")
                        .HasName("linha_producao_hora_etapa_funcionario_pkey");

                    b.HasIndex("Funcionario")
                        .HasDatabaseName("ix_linha_producao_hora_etapa_funcionario_funcionario");

                    b.ToTable("linha_producao_hora_etapa_funcionario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Db.FuncionarioEntity", b =>
                {
                    b.HasOne("GambitoServer.Db.FuncionarioEntity", "EncarregadoNavigation")
                        .WithMany("InverseEncarregadoNavigation")
                        .HasForeignKey("Encarregado")
                        .HasConstraintName("funcionario_encarregado_fkey");

                    b.HasOne("GambitoServer.Db.FuncaoEntity", "FuncaoNavigation")
                        .WithMany("Funcionarios")
                        .HasForeignKey("Funcao")
                        .HasConstraintName("funcionario_funcao_fkey");

                    b.Navigation("EncarregadoNavigation");

                    b.Navigation("FuncaoNavigation");
                });

            modelBuilder.Entity("GambitoServer.Db.PedidoEntity", b =>
                {
                    b.HasOne("GambitoServer.Db.ProdutoEntity", "ProdutoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("Produto")
                        .IsRequired()
                        .HasConstraintName("pedido_produto_fkey");

                    b.Navigation("ProdutoNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoDiaEntity", b =>
                {
                    b.HasOne("GambitoServer.LinhaProducao.LinhaProducaoEntity", "LinhaProducaoNavigation")
                        .WithMany("LinhaProducaoDia")
                        .HasForeignKey("LinhaProducao")
                        .IsRequired()
                        .HasConstraintName("linha_producao_dia_linha_producao_fkey");

                    b.Navigation("LinhaProducaoNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoHoraDefeitoEntity", b =>
                {
                    b.HasOne("GambitoServer.Db.DefeitoEntity", "DefeitoNavigation")
                        .WithMany("LinhaProducaoHoraDefeitos")
                        .HasForeignKey("Defeito")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_defeito_defeito_fkey");

                    b.HasOne("GambitoServer.LinhaProducao.LinhaProducaoHoraEntity", "LinhaProducaoHoraNavigation")
                        .WithMany("LinhaProducaoHoraDefeitos")
                        .HasForeignKey("LinhaProducaoHora")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_defeito_linha_producao_hora_fkey");

                    b.Navigation("DefeitoNavigation");

                    b.Navigation("LinhaProducaoHoraNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoHoraEntity", b =>
                {
                    b.HasOne("GambitoServer.Db.PedidoEntity", "PedidoNavigation")
                        .WithMany("LinhaProducaoHoras")
                        .HasForeignKey("Pedido")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_pedido_fkey");

                    b.HasOne("GambitoServer.LinhaProducao.LinhaProducaoDiaEntity", "LinhaProducaoDiaNavigation")
                        .WithMany("LinhaProducaoHoras")
                        .HasForeignKey("LinhaProducao", "Data")
                        .HasConstraintName("linha_producao_hora_linha_producao_data_fkey");

                    b.Navigation("LinhaProducaoDiaNavigation");

                    b.Navigation("PedidoNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoHoraEtapaEntity", b =>
                {
                    b.HasOne("GambitoServer.Db.EtapaEntity", "EtapaNavigation")
                        .WithMany("LinhaProducaoHoraEtapas")
                        .HasForeignKey("Etapa")
                        .HasConstraintName("linha_producao_hora_etapa_etapa_fkey");

                    b.HasOne("GambitoServer.LinhaProducao.LinhaProducaoHoraEntity", "LinhaProducaoHoraNavigation")
                        .WithMany("LinhaProducaoHoraEtapas")
                        .HasForeignKey("LinhaProducaoHora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_etapa_linha_producao_hora_fkey");

                    b.Navigation("EtapaNavigation");

                    b.Navigation("LinhaProducaoHoraNavigation");
                });

            modelBuilder.Entity("LinhaProducaoHoraEtapaFuncionario", b =>
                {
                    b.HasOne("GambitoServer.Db.FuncionarioEntity", null)
                        .WithMany()
                        .HasForeignKey("Funcionario")
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_etapa_funcionario_funcionario_fkey");

                    b.HasOne("GambitoServer.LinhaProducao.LinhaProducaoHoraEtapaEntity", null)
                        .WithMany()
                        .HasForeignKey("LinhaProducaoHoraEtapa")
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_etapa_funcio_linha_producao_hora_etapa_fkey");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GambitoServer.Db.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GambitoServer.Db.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("GambitoServer.Db.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GambitoServer.Db.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("GambitoServer.Db.DefeitoEntity", b =>
                {
                    b.Navigation("LinhaProducaoHoraDefeitos");
                });

            modelBuilder.Entity("GambitoServer.Db.EtapaEntity", b =>
                {
                    b.Navigation("LinhaProducaoHoraEtapas");
                });

            modelBuilder.Entity("GambitoServer.Db.FuncaoEntity", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("GambitoServer.Db.FuncionarioEntity", b =>
                {
                    b.Navigation("InverseEncarregadoNavigation");
                });

            modelBuilder.Entity("GambitoServer.Db.PedidoEntity", b =>
                {
                    b.Navigation("LinhaProducaoHoras");
                });

            modelBuilder.Entity("GambitoServer.Db.ProdutoEntity", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoDiaEntity", b =>
                {
                    b.Navigation("LinhaProducaoHoras");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoEntity", b =>
                {
                    b.Navigation("LinhaProducaoDia");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao.LinhaProducaoHoraEntity", b =>
                {
                    b.Navigation("LinhaProducaoHoraDefeitos");

                    b.Navigation("LinhaProducaoHoraEtapas");
                });
#pragma warning restore 612, 618
        }
    }
}
