// <auto-generated />
using System;
using GambitoServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GambitoServer.Migrations
{
    [DbContext(typeof(GambitoContext.GambitoContext))]
    partial class GambitoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_hora", new[] { "HORA_EXTRA", "BANCO_HORAS" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GambitoServer.Defeito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("defeito_pkey");

                    b.HasIndex(new[] { "Nome" }, "defeito_nome_key")
                        .IsUnique();

                    b.ToTable("defeito", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("etapa_pkey");

                    b.ToTable("etapa", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Funcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("funcao_pkey");

                    b.HasIndex(new[] { "Nome" }, "funcao_nome_key")
                        .IsUnique();

                    b.ToTable("funcao", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("Encarregado")
                        .HasColumnType("integer")
                        .HasColumnName("encarregado");

                    b.Property<int?>("Funcao")
                        .HasColumnType("integer")
                        .HasColumnName("funcao");

                    b.Property<bool>("Invativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("funcionario_pkey");

                    b.HasIndex("Encarregado");

                    b.HasIndex("Funcao");

                    b.ToTable("funcionario", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("linha_producao_pkey");

                    b.ToTable("linha_producao", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoDium", b =>
                {
                    b.Property<int>("LinhaProducao")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<bool>("Invativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invativo");

                    b.HasKey("LinhaProducao", "Data")
                        .HasName("linha_producao_dia_pkey");

                    b.ToTable("linha_producao_dia", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoHora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora");

                    b.Property<TimeOnly?>("HoraFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim");

                    b.Property<TimeOnly?>("HoraIni")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_ini");

                    b.Property<int>("LinhaProducao")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao");

                    b.Property<bool>("Paralizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("paralizacao");

                    b.Property<int>("Pedido")
                        .HasColumnType("integer")
                        .HasColumnName("pedido");

                    b.Property<int?>("QtdProduzido")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_produzido");

                    b.Property<int?>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("linha_producao_hora_pkey");

                    b.HasIndex("Pedido");

                    b.HasIndex("LinhaProducao", "Data");

                    b.ToTable("linha_producao_hora", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoHoraDefeito", b =>
                {
                    b.Property<int>("LinhaProducaoHora")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao_hora");

                    b.Property<bool>("Retrabalhado")
                        .HasColumnType("boolean")
                        .HasColumnName("retrabalhado");

                    b.Property<int>("Defeito")
                        .HasColumnType("integer")
                        .HasColumnName("defeito");

                    b.Property<int>("QtdPecas")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_pecas");

                    b.HasKey("LinhaProducaoHora", "Retrabalhado", "Defeito")
                        .HasName("linha_producao_hora_defeito_pkey");

                    b.HasIndex("Defeito");

                    b.ToTable("linha_producao_hora_defeito", (string)null);
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoHoraEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int?>("Etapa")
                        .HasColumnType("integer")
                        .HasColumnName("etapa");

                    b.Property<int>("LinhaProducao")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Segundos")
                        .HasColumnType("integer")
                        .HasColumnName("segundos");

                    b.HasKey("Id")
                        .HasName("linha_producao_hora_etapa_pkey");

                    b.HasIndex("Etapa");

                    b.HasIndex("LinhaProducao", "Data");

                    b.ToTable("linha_producao_hora_etapa", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("Produto")
                        .HasColumnType("integer")
                        .HasColumnName("produto");

                    b.Property<int>("QtdPecas")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_pecas");

                    b.HasKey("Id")
                        .HasName("pedido_pkey");

                    b.HasIndex("Produto");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("TempoPeca")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_peca");

                    b.HasKey("Id")
                        .HasName("produto_pkey");

                    b.HasIndex(new[] { "Nome" }, "produto_nome_key")
                        .IsUnique();

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("LinhaProducaoHoraEtapaFuncionario", b =>
                {
                    b.Property<int>("LinhaProducaoHoraEtapa")
                        .HasColumnType("integer")
                        .HasColumnName("linha_producao_hora_etapa");

                    b.Property<int>("Funcionario")
                        .HasColumnType("integer")
                        .HasColumnName("funcionario");

                    b.HasKey("LinhaProducaoHoraEtapa", "Funcionario")
                        .HasName("linha_producao_hora_etapa_funcionario_pkey");

                    b.HasIndex("Funcionario");

                    b.ToTable("linha_producao_hora_etapa_funcionario", (string)null);
                });

            modelBuilder.Entity("GambitoServer.Funcionario", b =>
                {
                    b.HasOne("GambitoServer.Funcionario", "EncarregadoNavigation")
                        .WithMany("InverseEncarregadoNavigation")
                        .HasForeignKey("Encarregado")
                        .HasConstraintName("funcionario_encarregado_fkey");

                    b.HasOne("GambitoServer.Funcao", "FuncaoNavigation")
                        .WithMany("Funcionarios")
                        .HasForeignKey("Funcao")
                        .HasConstraintName("funcionario_funcao_fkey");

                    b.Navigation("EncarregadoNavigation");

                    b.Navigation("FuncaoNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoDium", b =>
                {
                    b.HasOne("GambitoServer.LinhaProducao", "LinhaProducaoNavigation")
                        .WithMany("LinhaProducaoDia")
                        .HasForeignKey("LinhaProducao")
                        .IsRequired()
                        .HasConstraintName("linha_producao_dia_linha_producao_fkey");

                    b.Navigation("LinhaProducaoNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoHora", b =>
                {
                    b.HasOne("GambitoServer.Pedido", "PedidoNavigation")
                        .WithMany("LinhaProducaoHoras")
                        .HasForeignKey("Pedido")
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_pedido_fkey");

                    b.HasOne("GambitoServer.LinhaProducaoDium", "LinhaProducaoDium")
                        .WithMany("LinhaProducaoHoras")
                        .HasForeignKey("LinhaProducao", "Data")
                        .HasConstraintName("linha_producao_hora_linha_producao_data_fkey");

                    b.Navigation("LinhaProducaoDium");

                    b.Navigation("PedidoNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoHoraDefeito", b =>
                {
                    b.HasOne("GambitoServer.Defeito", "DefeitoNavigation")
                        .WithMany("LinhaProducaoHoraDefeitos")
                        .HasForeignKey("Defeito")
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_defeito_defeito_fkey");

                    b.HasOne("GambitoServer.LinhaProducaoHora", "LinhaProducaoHoraNavigation")
                        .WithMany("LinhaProducaoHoraDefeitos")
                        .HasForeignKey("LinhaProducaoHora")
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_defeito_linha_producao_hora_fkey");

                    b.Navigation("DefeitoNavigation");

                    b.Navigation("LinhaProducaoHoraNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoHoraEtapa", b =>
                {
                    b.HasOne("GambitoServer.Etapa", "EtapaNavigation")
                        .WithMany("LinhaProducaoHoraEtapas")
                        .HasForeignKey("Etapa")
                        .HasConstraintName("linha_producao_hora_etapa_etapa_fkey");

                    b.HasOne("GambitoServer.LinhaProducaoDium", "LinhaProducaoDium")
                        .WithMany("LinhaProducaoHoraEtapas")
                        .HasForeignKey("LinhaProducao", "Data")
                        .HasConstraintName("linha_producao_hora_etapa_linha_producao_data_fkey");

                    b.Navigation("EtapaNavigation");

                    b.Navigation("LinhaProducaoDium");
                });

            modelBuilder.Entity("GambitoServer.Pedido", b =>
                {
                    b.HasOne("GambitoServer.Produto", "ProdutoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("Produto")
                        .IsRequired()
                        .HasConstraintName("pedido_produto_fkey");

                    b.Navigation("ProdutoNavigation");
                });

            modelBuilder.Entity("LinhaProducaoHoraEtapaFuncionario", b =>
                {
                    b.HasOne("GambitoServer.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("Funcionario")
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_etapa_funcionario_funcionario_fkey");

                    b.HasOne("GambitoServer.LinhaProducaoHoraEtapa", null)
                        .WithMany()
                        .HasForeignKey("LinhaProducaoHoraEtapa")
                        .IsRequired()
                        .HasConstraintName("linha_producao_hora_etapa_funcio_linha_producao_hora_etapa_fkey");
                });

            modelBuilder.Entity("GambitoServer.Defeito", b =>
                {
                    b.Navigation("LinhaProducaoHoraDefeitos");
                });

            modelBuilder.Entity("GambitoServer.Etapa", b =>
                {
                    b.Navigation("LinhaProducaoHoraEtapas");
                });

            modelBuilder.Entity("GambitoServer.Funcao", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("GambitoServer.Funcionario", b =>
                {
                    b.Navigation("InverseEncarregadoNavigation");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducao", b =>
                {
                    b.Navigation("LinhaProducaoDia");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoDium", b =>
                {
                    b.Navigation("LinhaProducaoHoraEtapas");

                    b.Navigation("LinhaProducaoHoras");
                });

            modelBuilder.Entity("GambitoServer.LinhaProducaoHora", b =>
                {
                    b.Navigation("LinhaProducaoHoraDefeitos");
                });

            modelBuilder.Entity("GambitoServer.Pedido", b =>
                {
                    b.Navigation("LinhaProducaoHoras");
                });

            modelBuilder.Entity("GambitoServer.Produto", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
