services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/:Z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    user: '$UID:$GID'
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/:Z

networks: 
  postgres-network:
    driver: bridge
